services:
  db:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    environment:
      MYSQL_DATABASE: db_troca_livros
      MYSQL_ROOT_PASSWORD: seu-password-super-secreto
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./back/Projeto-Livraria-backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./back/Projeto-Livraria-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: seu-password-super-secreto
      DB_NAME: db_troca_livros
      DB_PORT: 3306
    depends_on:
      - db
  frontend:
    build:
      context: ./front/Projeto-Livraria-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  mysql-data:
